embedding_size: 64
feat_embed_dim: 64
weight_size: [64, 64]

lambda_coeff: 0.9
reg_weight: [0.07,0.05,0.03]

n_mm_layers: 1
n_ui_layers: 2
knn_k: 10

mm_image_weight: 0.1
dropout: [0.9,0.85,0.8]
learning_rate: [0.002,0.001,0.0005,0.0003]
seed: [888]

hyper_parameters: ["dropout", "reg_weight","learning_rate"]
