embedding_size: 64
n_ui_layers: 2
n_layers: 1

learning_rate_scheduler: [0.96, 50]
lambda_coeff: 0.9
reg_weight: 1e-04

knn_k: 10

learning_rate: [0.005,0.001,0.0005,0.0001]

cl_loss: [0.0001,0.001,0.01,0.1,1.0]

hyper_parameters: ["cl_loss","learning_rate"]